### ISSUE TITLE
End Portal Not Generating

### ISSUE THREAD

**Issue by JavaJes** [DerFrZocker/Chunk-Remover#1]
I'm seeing issues with the End Portal not being generated in empty chunks when inserting the "generate-portal-room" config value. Is this a currently implemented feature? I ask because it wasn't listed in the default config.yml file, but did exist in source code.

Here is an example of my config file:
````
world-datas:
  world:
    chunk-validator:
      name: "random"
      data:
        name-seeded: false # true: the resulting pattern is dependent on the world seed and name
        # false: the resulting pattern is dependent only on the world seed
        chance: 99.0 # The chance that a chunk is an empty chunk from 0 (no chunk gets removed) to 100 (all chunks are getting removed)
        # In this case 70% of the world is removed
    generate-portal-room: true # Generate the world's portal room
  world_nether:
    chunk-validator:
      name: "random"
      data:
        name-seeded: false
        chance: 99.0
`````
